_itemsSource["unique"] = {
	{
		name = "mint_mate_chain",
		label = "Mint Mate Chain",
		description = "It's Mint Mate",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "mint_mate",
		iconOverride = "rlg_chain",
	},
	{
		name = "mint_mate_chain_2",
		label = "Mint Mate Chain (Large)",
		description = "It's Mint Mate ... but large",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "mint_mate2",
		iconOverride = "rlg_chain",
	},
	{
		name = "ssb_chain",
		label = "SSB Chain",
		description = "SSB Gang Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ssb",
		iconOverride = "rlg_chain",
	},
}
