_itemsSource["weapons_base"] = {
	{
		name = "WEAPON_SMG",
		label = "SMG",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_MP5",
		weapon = "WEAPON_MP5",
		iconOverride = "WEAPON_SMG",
		label = "MP5",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_PP19",
		label = "PP-19",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_MP9A",
		weapon = "WEAPON_MP9A",
		label = "MP9",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_MPX",
		label = "MPX",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_MINIUZI",
		label = "Mini Uzi",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_BALL",
		label = "Ball",
		ammoType = "AMMO_BALL",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		isThrowable = true,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_SNOWBALL",
		label = "Snowball",
		ammoType = "AMMO_SNOWBALL",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		isThrowable = true,
		durability = (60 * 60 * 24),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_GRENADE",
		label = "Grenade",
		ammoType = "AMMO_GRENADE",
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_BZGAS",
		label = "BZ Gas",
		ammoType = "AMMO_BZGAS",
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_MOLOTOV",
		label = "Molotov",
		ammoType = "AMMO_MOLOTOV",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 5,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 2,
	},
	{
		name = "WEAPON_STICKYBOMB",
		label = "C4",
		ammoType = "AMMO_STICKYBOMB",
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = "WEAPON_PROXMINE",
		label = "Proximity Mine",
		ammoType = "AMMO_PROXMINE",
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = "WEAPON_PIPEBOMB",
		label = "Pipe Bomb",
		ammoType = "AMMO_PIPEBOMB",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 7),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = "WEAPON_SMOKEGRENADE",
		label = "Smoke Grenade",
		ammoType = "AMMO_SMOKEGRENADE",
		qualification = "PD_SWAT",
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		storeStack = 1,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 1,
	},
	{
		name = "WEAPON_FLASHBANG",
		label = "Flashbang",
		ammoType = "AMMO_FLASH",
		qualification = "PD_SWAT",
		requiresLicense = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		storeStack = 1,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 4,
		closeUi = true,
		metalic = true,
		weight = 1,
	},
	{
		name = "WEAPON_FLARE",
		label = "Flare",
		ammoType = "AMMO_FLARE",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isThrowable = true,
		isUsable = true,
		isRemoved = true,
		isStackable = 10,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 14),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_FIREEXTINGUISHER",
		label = "Fire Extinguisher",
		ammoType = "AMMO_FIREEXTINGUISHER",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 21),
		type = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_PETROLCAN",
		label = "Petrol Can",
		ammoType = "AMMO_PETROLCAN",
		requiresLicense = false,
		noSerial = true,
		price = 150,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_CROWBAR",
		label = "Crowbar",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_BAT",
		label = "Baseball Bat",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_LUCILLE",
		label = "Lucille",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_DRBAT",
		label = "Dr-Deshbat",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_CRUTCH",
		label = "Crutch",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_SLEDGE",
		label = "Sledge Hammer",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 12,
	},
	{
		name = "WEAPON_SHOVEL",
		label = "Shovel",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_DAGGER",
		label = "Dagger",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_MACHETE",
		label = "Machete",
		requiresLicense = false,
		noSerial = true,
		price = 700,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_PONY",
		label = "Pony",
		requiresLicense = false,
		noSerial = true,
		price = 700,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_SLEDGE",
		label = "Sledgehammer",
		requiresLicense = false,
		noSerial = true,
		price = 700,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = "WEAPON_KNIFE",
		label = "Knife",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8.5,
	},
	{
		name = "WEAPON_SWITCHBLADE",
		label = "Switchblade",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8,
	},
	{
		name = "WEAPON_BOTTLE",
		label = "Broken Bottle",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8,
	},
	{
		name = "WEAPON_WRENCH",
		label = "Pipe Wrench",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_BATTLEAXE",
		label = "Battle Axe",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 18,
	},
	{
		name = "WEAPON_HATCHET",
		label = "Hatchet",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 18,
	},
	{
		name = "WEAPON_STONE_HATCHET",
		label = "Stone Hatchet",
		requiresLicense = false,
		noSerial = true,
		price = 300,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 12,
	},
	{
		name = "WEAPON_HAMMER",
		label = "Hammer",
		requiresLicense = false,
		noSerial = true,
		price = 500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_GOLFCLUB",
		label = "Golf Club",
		requiresLicense = false,
		noSerial = true,
		price = 500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 12,
	},
	{
		name = "WEAPON_KNUCKLE",
		label = "Knuckle Dusters",
		requiresLicense = false,
		noSerial = true,
		price = 400,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 7.5,
	},
	{
		name = "WEAPON_POOLCUE",
		label = "Pool Cue",
		requiresLicense = false,
		noSerial = true,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 5,
	},
	{
		name = "WEAPON_FLASHLIGHT",
		label = "Flashlight",
		requiresLicense = false,
		noSerial = true,
		price = 75,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8,
	},
	{
		name = "WEAPON_NIGHTSTICK",
		label = "Nightstick",
		requiresLicense = false,
		noSerial = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 8,
	},
	{
		name = "WEAPON_PISTOL",
		label = "Berretta M92",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 2000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_COMBATPISTOL",
		label = "Combat Pistol",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_FNX",
		label = "FNX-45",
		ammoType = "AMMO_PISTOL",
		weapon = "WEAPON_FNX45",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_FNX45",
		label = "FNX-45",
		ammoType = "AMMO_PISTOL",
		iconOverride = "WEAPON_FNX",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_APPISTOL",
		label = "Glock 18C",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_VINTAGEPISTOL",
		label = "Vintage Pistol",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 5500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_HEAVYPISTOL",
		label = "Heavy Pistol",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_P320A",
		label = "P320a",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_SNSPISTOL",
		label = "SNS Pistol",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 2,
		closeUi = true,
		metalic = true,
		weight = 8,
		gun = true,
	},
	{
		name = "WEAPON_SNSPISTOL_MK2",
		label = "SNS Pistol MK2",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 4500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 8,
		gun = true,
	},
	{
		name = "WEAPON_FLAREGUN",
		label = "Flare Pistol",
		ammoType = "AMMO_FLAREGUN",
		requiresLicense = false,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_MARKSMANPISTOL",
		label = "Marksman Pistol",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 7500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_REVOLVER",
		label = "Colt Python",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 7000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_REVOLVER_MK2",
		label = "Chiappa Rhino",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 7000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_DOUBLEACTION",
		label = "Colt M1892",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 8000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_PISTOL50",
		label = "Desert Eagle",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_PISTOL_MK2",
		label = "Pistol MK2",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 2500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_MICROSMG",
		label = "MAC-10",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = "WEAPON_UZI",
		label = "Uzi",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = "WEAPON_MINISMG",
		label = "Skorpion",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isDestroyed = false,
		isStackable = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = "WEAPON_SMG_MK2",
		label = "SMG MK2",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = "WEAPON_ASSAULTSMG",
		label = "P90",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_COMBATPDW",
		label = "Combat PDW",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MACHINEPISTOL",
		label = "TEC-9",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = "WEAPON_GUSENBERG",
		label = "Tommy Gun",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MG",
		label = "PKM",
		ammoType = "AMMO_MG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 20,
		gun = true,
	},
	{
		name = "WEAPON_COMBATMG",
		label = "LMG",
		ammoType = "AMMO_MG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 20,
		gun = true,
	},
	{
		name = "WEAPON_COMBATMG_MK2",
		label = "M60E4",
		ammoType = "AMMO_MG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 20,
		gun = true,
	},
	{
		name = "WEAPON_MUSKET",
		label = "Musket",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_BEANBAG",
		label = "Beanbag Shotgun",
		ammoType = "AMMO_SHOTGUN",
		qualification = "PD_BEANBAG",
		requiresLicense = true,
		price = 300,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_SAWNOFFSHOTGUN",
		label = "Sawn Off Shotgun",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 12,
		gun = true,
	},
	{
		name = "WEAPON_PUMPSHOTGUN",
		label = "Mossberg 590",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_PUMPSHOTGUN_MK2",
		label = "Remington 870",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_BULLPUPSHOTGUN",
		label = "Kel-Tec KSG",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_ASSAULTSHOTGUN",
		label = "UTS-15",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_DBSHOTGUN",
		label = "Double Barrel Shotgun",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_HEAVYSHOTGUN",
		label = "Assault Shotgun",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_AUTOSHOTGUN",
		label = "Auto Shotgun",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_ASSAULTRIFLE",
		label = "AK-47",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_AK74",
		label = "AK-74",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_50BEOWULF",
		label = ".50 Beowulf",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_AR15",
		label = "AR-15",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_FIVESEVEN",
		label = "Five Seven",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_P90FM",
		label = "P90",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_HKUMP",
		label = "UMP-45",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 3),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_ASSAULTRIFLE_MK2",
		label = "AK-12",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_CARBINERIFLE",
		label = "M4A1",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_CARBINERIFLE_MK2",
		label = "AR-15",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_COMPACTRIFLE",
		label = "Draco",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_BULLPUPRIFLE",
		label = "Bullpup Rifle",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_BULLPUPRIFLE_MK2",
		label = "Bullpup Rifle MK2",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_ADVANCEDRIFLE",
		label = "Kel-Tec RFB",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_SPECIALCARBINE",
		label = "G36",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_SPECIALCARBINE_MK2",
		label = "G36K",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_SNIPERRIFLE",
		label = "L96A1",
		ammoType = "AMMO_SNIPER",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MARKSMANRIFLE",
		label = "M39 EMR",
		ammoType = "AMMO_SNIPER",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MARKSMANRIFLE_MK2",
		label = "MK-12",
		ammoType = "AMMO_SNIPER",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_HEAVYSNIPER",
		label = "Barrett M82",
		ammoType = "AMMO_SNIPER",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_HEAVYSNIPER_MK2",
		label = "Serbu BFG-50A",
		ammoType = "AMMO_SNIPER",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_GRENADELAUNCHER_SMOKE",
		label = "Grenade Launcher",
		ammoType = "AMMO_GRENADELAUNCHER_SMOKE",
		requiresLicense = true,
		price = 100000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 20,
	},
	{
		name = "WEAPON_FIREWORK",
		label = "Firework Launcher",
		ammoType = "AMMO_FIREWORK",
		requiresLicense = false,
		price = 100000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 20,
	},
	-- {
	-- 	name = "WEAPON_STUNGUN",
	-- 	label = "Stun Gun",
	-- 	ammoType = "AMMO_STUNGUN",
	-- 	requiresLicense = false,
	-- 	price = 1000,
	-- 	isUsable = true,
	-- 	isRemoved = false,
	-- 	isStackable = false,
	-- 	isDestroyed = false,
	-- 	durability = (60 * 60 * 24 * 21),
	-- 	type = 2,
	-- 	rarity = 1,
	-- 	closeUi = true,
	-- 	metalic = true,
	-- 	weight = 1,
	-- },
	{
		name = "WEAPON_TASER",
		label = "Taser",
		ammoType = "AMMO_STUNGUN",
		requiresLicense = false,
		price = 200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
	},
	{
		name = "WEAPON_SNIPERRIFLE2",
		label = "Hunting Rifle",
		ammoType = "AMMO_SNIPER",
		requiresLicense = true,
		price = 1000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_KATANAS",
		label = "Katana",
		ammoType = "NONE",
		requiresLicense = false,
		price = 2000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 3,
	},
	{
		name = "WEAPON_SHIV",
		label = "Shiv",
		ammoType = "NONE",
		requiresLicense = false,
		price = 2000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 0.5,
	},
	{
		name = "WEAPON_L5",
		label = "Desert Eagle K8",
		iconOverride = "WEAPON_PISTOL50",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_P3200A",
		label = "P320 X Five",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	-- {
	-- 	name = "WEAPON_GLOCK19_CIV",
	-- 	label = "Glock 19",
	-- 	iconOverride = "WEAPON_GLOCK19",
	-- 	ammoType = "AMMO_PISTOL",
	-- 	requiresLicense = true,
	-- 	price = 6000,
	-- 	isUsable = true,
	-- 	isRemoved = false,
	-- 	isStackable = false,
	-- 	isDestroyed = false,
	-- 	durability = (60 * 60 * 24 * 21),
	-- 	type = 2,
	-- 	rarity = 3,
	-- 	closeUi = true,
	-- 	metalic = true,
	-- 	weight = 5,
	-- 	gun = true,
	-- },
	{
		name = "WEAPON_M45A1",
		label = "M45A1",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_2011",
		label = "STI DVC 2011",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_G36",
		label = "G36",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_RPK16",
		label = "RPK-16",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_GLOCK19",
		label = "Glock 19",
		iconOverride = "WEAPON_GLOCK19",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 6000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	-- {
	-- 	name = "WEAPON_HKUMP_PD",
	-- 	label = "PD .45 SMG",
	-- 	ammoType = "AMMO_SMG",
	-- 	qualification = "PD_SMG",
	-- 	iconOverride = "WEAPON_HKUMP",
	-- 	requiresLicense = true,
	-- 	price = 10000,
	-- 	isUsable = true,
	-- 	isRemoved = false,
	-- 	isStackable = false,
	-- 	isDestroyed = false,
	-- 	durability = (60 * 60 * 24 * 3),
	-- 	type = 2,
	-- 	rarity = 3,
	-- 	closeUi = true,
	-- 	metalic = true,
	-- 	weight = 15,
	-- 	gun = true,
	-- },
	-- {
	-- 	name = "WEAPON_AR15_PD",
	-- 	label = "PD 56A1",
	-- 	ammoType = "AMMO_RIFLE",
	-- 	iconOverride = "WEAPON_AR15",
	-- 	qualification = "PD_AR",
	-- 	requiresLicense = true,
	-- 	price = 10000,
	-- 	isUsable = true,
	-- 	isRemoved = false,
	-- 	isStackable = false,
	-- 	isDestroyed = false,
	-- 	durability = (60 * 60 * 24 * 3),
	-- 	type = 2,
	-- 	rarity = 3,
	-- 	closeUi = true,
	-- 	metalic = true,
	-- 	weight = 15,
	-- 	gun = true,
	-- },
	{
		name = "WEAPON_FM1_HONEYBADGER",
		label = "Honey Badger",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_ASVAL",
		label = "AS-VAL",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_DOUBLEBARRELFM",
		label = "Double Barrel FM",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_FM1_HK416",
		label = "HK416 FM1",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_FM2_HK416",
		label = "HK416 FM2",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_HK417",
		label = "HK-417",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_PM4",
		label = "PM4A1",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_FM1_M9A3",
		label = "M9A3",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_M249",
		label = "M249",
		ammoType = "AMMO_MG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MCXRATTLER",
		label = "MCX Rattler",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MCXSPEAR",
		label = "MCX Spear",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MK14",
		label = "MK-14 EBR",
		ammoType = "AMMO_SNIPER",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MK-47FM",
		label = "MK-47 Mutant",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MK-47BANSHEE",
		label = "MK-47 Banshee S",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_MK-47BANSHEE2",
		label = "MK-47 Banshee A",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_NSR9",
		label = "NSR-9",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_RFB",
		label = "RFB",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_VECTOR",
		label = "Fennec",
		ammoType = "AMMO_SMG",
		requiresLicense = true,
		price = 10000,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 3,
		closeUi = true,
		metalic = true,
		weight = 15,
		gun = true,
	},
	{
		name = "WEAPON_BENELLIM2",
		label = "Benelli M2",
		ammoType = "AMMO_SHOTGUN",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	-- {
	-- 	name = "WEAPON_BENELLIM2_PD",
	-- 	label = "PD BM2",
	-- 	ammoType = "AMMO_SHOTGUN",
	-- 	requiresLicense = true,
	-- 	qualification = "PD_BEANBAG",
	-- 	price = 3200,
	-- 	isUsable = true,
	-- 	isRemoved = false,
	-- 	isStackable = false,
	-- 	isDestroyed = false,
	-- 	durability = (60 * 60 * 24 * 21),
	-- 	type = 2,
	-- 	rarity = 1,
	-- 	closeUi = true,
	-- 	metalic = true,
	-- 	weight = 5,
	-- 	gun = true,
	-- },
	{
		name = "WEAPON_FN509",
		label = "FN-509",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_FM1_CZ75",
		label = "CZ75 FM1",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_FM1_P226",
		label = "P226 FM1",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_SWMP9",
		label = "SW NQ9",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_MB47",
		label = "AK-47",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_SA80",
		label = "L95",
		ammoType = "AMMO_RIFLE",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_38SNUBNOSE",
		label = ".38 Snubnose",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_38SNUBNOSE2",
		iconOverride = "WEAPON_38SNUBNOSE",
		label = ".38 Snubnose",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_38SNUBNOSE3",
		iconOverride = "WEAPON_38SNUBNOSE",
		label = ".38 Snubnose",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_38SPECIAL",
		label = ".38 Special",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_44MAGNUM",
		label = ".44 Magnum",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
	{
		name = "WEAPON_44MAGNUM_PD",
		label = "PD .44 Magnum",
		iconOverride = "WEAPON_44MAGNUM",
		ammoType = "AMMO_PISTOL",
		requiresLicense = true,
		price = 3200,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		isDestroyed = false,
		durability = (60 * 60 * 24 * 21),
		type = 2,
		rarity = 1,
		closeUi = true,
		metalic = true,
		weight = 5,
		gun = true,
	},
}
