_itemsSource["unique"] = {
	{
		name = "mint_mate_chain",
		label = "Mint Mate Chain",
		description = "It's Mint Mate",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "mint_mate",
		iconOverride = "rlg_chain",
	},
	{
		name = "mint_mate_chain_2",
		label = "Mint Mate Chain (Large)",
		description = "It's Mint Mate ... but large",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "mint_mate2",
		iconOverride = "rlg_chain",
	},
	{
		name = "ssb_chain",
		label = "SSB Chain",
		description = "SSB Gang Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ssb",
		iconOverride = "rlg_chain",
	},
	{
		name = "gotti_chain",
		label = "Gotti Family Chain",
		description = "Gotti Family Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "gotti",
		iconOverride = "rlg_chain",
	},
	{
		name = "uwu_chain",
		label = "UwU Chain",
		description = "UwU Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "uwu",
		iconOverride = "rlg_chain",
	},
	{
		name = "pixels_chain",
		label = "Business Bureau Chain",
		description = "Business Bureau Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "lua",
		iconOverride = "rlg_chain",
	},
	{
		name = "frosty_chain",
		label = "Frosty Chain",
		description = "Frosty Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "frosty",
		iconOverride = "rlg_chain",
	},
	{
		name = "milk_chain",
		label = "Milk Chain",
		description = "Milk Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "milk",
		iconOverride = "rlg_chain",
	},
	{
		name = "saint_chain",
		label = "Saint Chain",
		description = "Saint Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "saint",
		iconOverride = "rlg_chain",
	},
	{
		name = "bobs_chain",
		label = "Bob's Balls Chain",
		description = "Bob's Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "bobs",
		iconOverride = "rlg_chain",
	},
	{
		name = "lala_chain",
		label = "Tequi-La-La Chain",
		description = "Tequi-La-La Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "lala",
		iconOverride = "rlg_chain",
	},
	{
		name = "rooks_chain",
		label = "Rooks Chain",
		description = "Rooks Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "rooks",
		iconOverride = "rlg_chain",
	},
	{
		name = "deathrow_chain",
		label = "Death Row Chain",
		description = "Death Row Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "deathrow",
		iconOverride = "rlg_chain",
	},
	{
		name = "ferrari_chain",
		label = "Ferrari Family Chain",
		description = "Ferrari Family Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ferrari",
		iconOverride = "rlg_chain",
	},
	{
		name = "dynasty_chain",
		label = "Dynasty Chain",
		description = "Dynasty Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "dynasty",
		iconOverride = "rlg_chain",
	},
	{
		name = "oni_chain",
		label = "Oni Chain",
		description = "Oni Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "oni",
		iconOverride = "rlg_chain",
	},
	{
		name = "snowboiz_chain",
		label = "Snow Boiz Chain",
		description = "Snow Boiz Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "snowboiz",
		iconOverride = "rlg_chain",
	},
	{
		name = "mint_mate_chain_3",
		label = "Mint Mate Chain (Alternate)",
		description = "It's Mint Mate",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 15,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "mint_mate3",
		iconOverride = "rlg_chain",
	},
	{
		name = "boo_chain",
		label = "BOO Chain",
		description = "BOO!",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "boo",
		iconOverride = "rlg_chain",
	},
	{
		name = "krazed_chain",
		label = "Krazed Ridez Chain",
		description = "Krazed Ridez Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "krazed",
		iconOverride = "rlg_chain",
	},
	{
		name = "snow_chain",
		label = "Snow Chain",
		description = "Snow Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "snow",
		iconOverride = "rlg_chain",
	},
	{
		name = "rush_chain",
		label = "Rush Chain",
		description = "Rush Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "rush",
		iconOverride = "rlg_chain",
	},
	{
		name = "meg_chain",
		label = "Meg Chain",
		description = "Meg Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "meg",
		iconOverride = "rlg_chain",
	},
	{
		name = "olivia_chain",
		label = "Vangelico Chain",
		description = "Vangelico Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "olivia",
		iconOverride = "rlg_chain",
	},
	{
		name = "diamond_chain",
		label = "Olivia Chain",
		description = "Olivia Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "diamond",
		iconOverride = "rlg_chain",
	},
	{
		name = "britton_chain",
		label = "Britton Chain",
		description = "Britton Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "britton",
		iconOverride = "rlg_chain",
	},
	{
		name = "ssf_chain",
		label = "SSF Chain",
		description = "SSF Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "ssf",
		iconOverride = "rlg_chain",
	},
	{
		name = "bigpoppa_chain",
		label = "Big Poppa Chain",
		description = "Big Poppa Chain",
		price = 50,
		isUsable = true,
		isRemoved = true,
		isStackable = false,
		type = 5,
		rarity = 4,
		closeUi = true,
		metalic = false,
		weight = 0,
		gangChain = "bigpoppa",
		iconOverride = "rlg_chain",
	},
}
