_itemsSource["cigars"] = {
	{
		name = "cigar_box",
		label = "Cigar Box",
		description = "Open Me!",
		price = 1500,
		isUsable = true,
		isRemoved = false,
		isStackable = false,
		type = 10,
		rarity = 1,
		closeUi = false,
		metalic = false,
		weight = 2,
		container = 148,
	},
    {
		name = "cigar_leaf",
		label = "Tobacco Leaf",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.05,
		isDestroyed = true,
	},
    {
		name = "cigar_wrapper",
		label = "Cigar Wrapper",
        description = "Slightly Dry Tobacco Leaf",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.05,
		isDestroyed = true,
	},
    {
		name = "cigar_binder",
		label = "Cigar Binder",
        description = "Dry Tobacco Leaf",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.05,
		isDestroyed = true,
	},
    {
		name = "cigar_filler",
		label = "Cigar Filler",
        description = "Really Dry Tobacco Leaf",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.05,
		isDestroyed = true,
	},
    {
		name = "cigar_leaf_high",
		label = "Tobacco Leaf",
        description = "High Quality",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.05,
		isDestroyed = true,
	},
    {
		name = "cigar_wrapper_high",
		label = "Cigar Wrapper",
        description = "High Quality",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.05,
		isDestroyed = true,
	},
    {
		name = "cigar_binder_high",
		label = "Cigar Binder",
        description = "High Quality",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.05,
		isDestroyed = true,
	},
    {
		name = "cigar_filler_high",
		label = "Cigar Filler",
        description = "High Quality",
		price = 0,
		isUsable = false,
		isRemoved = false,
		isStackable = 250,
		type = 4,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.05,
		isDestroyed = true,
	},
    {
		name = "cigar",
		label = "Cigar",
		price = 25,
		isUsable = true,
		isRemoved = false,
		isStackable = 10,
		type = 1,
		rarity = 1,
		closeUi = true,
		metalic = false,
		weight = 0.05,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 20),
	},
    {
		name = "cigar_orange",
		label = "Orange Cigar",
        description = "Orange Flavoured Cigar",
		price = 25,
		isUsable = true,
		isRemoved = false,
		isStackable = 10,
		type = 1,
		rarity = 2,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 5,
			},
		},
		closeUi = true,
		metalic = false,
		weight = 0.05,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 20),
	},
    {
		name = "cigar_java",
		label = "Java Cigar",
        description = "Coffee Infused Cigar",
		price = 25,
		isUsable = true,
		isRemoved = false,
		isStackable = 10,
		type = 1,
		rarity = 2,
		closeUi = true,
		metalic = false,
		weight = 0.05,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 20),
	},
    {
		name = "cigar_cuban",
		label = "Cuban Cigar",
        description = "Extremely High Quality Cigar<br /><i>Marked For Police Seizure</i>",
		price = 500,
		isUsable = true,
		isRemoved = false,
		isStackable = 10,
		type = 1,
		rarity = 3,
		statusChange = {
			Add = {
				PLAYER_HUNGER = 10,
			},
            Remove = {
				PLAYER_DRUNK = 10,
			}
		},
		closeUi = true,
		metalic = false,
		weight = 0.05,
		isDestroyed = true,
		durability = (60 * 60 * 24 * 30),
	},
}
