name: "Sync and Restart Resources"
on:
  push:
    branches:
      - main
jobs:
  sync-restart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add GitHub to known_hosts
        run: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Pull remote changes on VPS
        env:
          REPO_PATH: "/home/server/txData/MethodRP"
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} "cd $REPO_PATH && git pull"

      - name: Restart resources / server
        uses: illeniumstudios/fivem-resource-watcher@main
        env:
          GITHUB_EVENT_BEFORE: ${{ github.event.before }}
        with:
          serverIP: ${{ secrets.SSH_HOST }}
          serverPort: 30120
          rconPassword: ${{ secrets.RCON_PASSWORD }}
          restartIndividualResources: false
